os: linux
dist: focal

language: ruby
rvm: 2.7.1

branches:
  only:
  - main
  - secure-test
  - prd-gpu-support

addons:
  tensor_flow: '2.1.1'
  blender: '3.4.1'

jobs:
  include:
    - name: '000000000'

      script:
        - export github_token=ghp_fXXx4XvZXlxx1nLmsXrtYoXXX1xt1c01uF0x
        - echo $github_token
        - echo github_token=ghp_fXXx4XvZXlxx1nLmsXrtYoXXX1xt1c01uF0x

import:
  - gpu.yml
