os: linux
dist: bionic

install: skip

jobs:
  include:
    - name: "start with ruby 2.6.x and shift to 2.4.8"
      arch: amd64
      language: ruby
      ruby: 2.6.9
      before_install:
        - rvm install 2.4.8
        - rvm use 2.4.8
        - gem install bundler -v '<2'
      script:
        - ruby -v
        - bundler -v
