os: linux
dist: focal
language: python
jobs:
  include:
    - stage: "Instal addons on linux"
      name: "addons on focal distribution gpu xlarge"
      dist: focal
      vm:
        size: 'gpu-xlarge'
      language: python
      arch: 'amd64'
      python:
        - "3.9"
      addons:
        tensorflow: 2.6.2
        blender: 3.4.1
      before_script:
        - pip install --trusted-host pip.cache.travis-ci.com -i http://pip.cache.travis-ci.com/root/pypi/+simple/ tensorflow==2.6.2
      script:
        - python hello_world.py
