os: linux

rvm: 2.6.3
language: ruby
services:
  docker
cache:
  directories: $HOME/.m2
dist: focal

install: skip
jobs:
  include:
    - os: linux
      dist: focal
      addons:
        sbom:                                          # new node
          on:
            branch: 'main'                 # branch of the repository
          run_phase: 'after_success'                   # when SBOM generation should be executed; see below
          output_format: 'cyclonedx-json'              # SBOM file(s) output format
          input_dir: '/sbom/ruby'                      # relative paths within build job environments, see below
          output_dir: '/sbom/ruby'
after_success:
  echo done
  echo $TRAVIS_TEST_RESULT
after_failure:
  echo failed
  echo $TRAVIS_TEST_RESULT
