os: linux

language: java
services:
  docker
cache:
  directories: $HOME/.m2
dist: bionic
keys:
  - SSH_KEY_FOR_SIGNING # must match the key identifier set in the UI

env:
    secret: “...” # encrypted COSIGN_PASSWORD

before_script: 
  - travis_key SSH_KEY_FOR_SIGNING cosign.key  le

script: 
  - cosign sign --key cosign.key [whatever_the_image_identifier_is]

install: skip
jobs:
  include:
    name: failing
    script: true

after_success:
  echo done
  echo $TRAVIS_TEST_RESULT
after_failure:
  echo failed
  echo $TRAVIS_TEST_RESULT
