os: linux

jobs:
  include:
    - dist: focal
      language: ruby
      script: ruby hello.rb
    - dist: focal
      language: node_js
      script: node hello.js
    - dist: focal
      language: python
      script: python hello.py
      
    - dist: bionic
      language: ruby
      script: ruby hello.rb
    - dist: bionic
      language: node_js
      script: node hello.js
    - dist: bionic
      language: python
      script: python hello.py
    
