jobs:
  include:
    - stage: "GPU - ADDONS"
      name: "ADDONS"
      dist: xenial
      vm:
        size: 'gpu-medium'
      arch: 'amd64'
      addons:
        tensor_flow: 1.6.0
        blender: 3.4.1
      script:
        - blender -v
        - echo "It is done"
    - stage: "GPU - windows - should not allow that - blender"
      dist: xenial
      language: bash
      name: "windows"
      addons:
        blender: 3.4.1
      vm:
        size: 'gpu-medium'
      os: 'windows'
      script:
        - echo "It is done"
    - stage: "GPU - windows - should not allow that - just gpu"
      dist: xenial
      language: bash
      name: "windows"
      vm:
        size: 'gpu-medium'
      os: 'windows'
      script:
        - echo "It is done"